busan-bus-api:
  key : NUg3JoF3qG4D0ta4dKvgz9lo4SMpZ03u1Rh1SLHQZcJUEDitfcC3vNeKGjMqVr9dW45y52Z9GWj2yQsMeggVLQ==
  url :
    base_url : http://apis.data.go.kr/6260000/BusanBIMS/busStopList
    arrival_url : http://apis.data.go.kr/6260000/BusanBIMS/stopArrByBstopid
    route_url : http://apis.data.go.kr/6260000/BusanBIMS/busInfoByRouteId


