spring:
  jpa:
    open-in-view: false
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-security.yml
      - classpath:application-busan-bus-api.yml
      - classpath:application-solar-api.yml
      - classpath:application-jwt.yml